config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :judges do
    resources :admissions
  end

end

app/models/judge.rb
class Judge < ActiveRecord::Base
has_many :admissions

  filterrific(
    default_filter_params: { sorted_by: 'name_asc' },
    available_filters: [
      :sorted_by
    ]
  )

scope :with_country_id, lambda { |country_ids|
  where(country_id: [*country_ids])
}

scope :search_query, lambda { |query|
  where("name LIKE '% #{query}'")
}

scope :sorted_by, lambda { |sort_option|
  # extract the sort direction from the param value.
  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
  case sort_option.to_s
  when /^court_/

    order("judges.court #{ direction }")
    when /^name_/

    # Simple sort on the name colums
    order("LOWER(reverse(split_part(judges.name, ' ', 1))) #{ direction }")
  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
}

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Name (z-a)', 'name_desc'],
      ['Court (a-z)', 'court_asc'],
      ['Court (z-a)', 'court_desc'],
    ]
  end

  def parse
    require 'rubygems'
    require 'nokogiri'
    require 'open-uri'

    (1..2873).each do |i| #2873
      begin
        page = Nokogiri::HTML(open("http://www.sudnarada.gov.sk/mps/Priznanie#{i}.html"))
      rescue OpenURI::HTTPError
        puts "404"
      else
        judge_name = page.css("table")[3].css("tr td span")[1].text
        judge_court = page.css("table")[3].css("tr td span")[3].text
        year = page.css("table")[3].css("tr td span")[7].text
        puts judge_name + " " + judge_court
        judge = Judge.find_or_create_by(name: judge_name, court: judge_court)
        admission = Admission.create(judge_id: judge.id, year: year)
        puts "STRANKA http://www.sudnarada.gov.sk/mps/Priznanie#{i}.html"
        (0..4).each do |table_index|
          category2 = page.css("table")[4].css("tr td h3")[table_index].text

          #tabulka pre konkretny typ admissionu
          inner_table = page.css("table")[4].css("tr td table")[table_index]

          if (!inner_table.nil?)

            #riadky v danej tabulke
            rows = inner_table.css("tr")

            @admission_type = 0
            case category2
              when "Nehnuteľný majetok"
                @admission_type = 1
                rows.each do |row|
                  if (row.css("div.sbjp").text != "")
                    puts "ADMISSION TYPE #{@admission_type}: \n Nehnutelnost: #{row.css("div.sbjp")[0].text}
                         \n Nadobudnutie: #{row.css("div.sbjp")[1].text}
                         \n Datum: #{row.css("div.sbjp")[2].text}
                         \n Zmena: #{row.css("div.sbjp")[3].text}"
                    AdmissionItem.create(admission_id: admission.id, name: row.css("div.sbjp")[0].text, change: row.css("div.sbjp")[3].text, acquisition_date: row.css("div.sbjp")[2].text, acquisition_reason: row.css("div.sbjp")[1].text, category: "estate")
                  end
                end
              when "Hnuteľný majetok"
                @admission_type = 2
                rows.each do |row|
                  if (row.css("div.sbjp").text != "")
                    puts "ADMISSION TYPE #{@admission_type}: \n Hnutelnost: #{row.css("div.sbjp")[0].text}
                         \n Nadobudnutie: #{row.css("div.sbjp")[1].text}
                         \n Datum: #{row.css("div.sbjp")[2].text}
                         \n Cena: #{row.css("div.sbjp")[3].text}
                         \n Zmena: #{row.css("div.sbjp")[4].text}"
                    AdmissionItem.create(admission_id: admission.id, name: row.css("div.sbjp")[0].text, value: row.css("div.sbjp")[3].text, change: row.css("div.sbjp")[4].text, acquisition_date: row.css("div.sbjp")[2].text, acquisition_reason: row.css("div.sbjp")[1].text, category: "chattel")
                  end
                end
              when "Majetkové práva"
                @admission_type = 3
                rows.each do |row|
                  if (row.css("div.sbjp").text != "" and !row.css("div.sbjp")[4].nil?)
                    puts "ADMISSION TYPE #{@admission_type}: \n Popis prava: #{row.css("div.sbjp")[0].text}
                         \n Nadobudnutie: #{row.css("div.sbjp")[1].text}
                         \n Datum: #{row.css("div.sbjp")[2].text}
                         \n Cena: #{row.css("div.sbjp")[3].text}
                         \n Zmena: #{row.css("div.sbjp")[4].text}"
                    AdmissionItem.create(admission_id: admission.id, name: row.css("div.sbjp")[0].text, value: row.css("div.sbjp")[3].text, change: row.css("div.sbjp")[4].text, acquisition_date: row.css("div.sbjp")[2].text, acquisition_reason: row.css("div.sbjp")[1].text, category: "property_rights")
                  end
                end
              when "Závazky predmetom ktorých je peňažné plnenie"
                @admission_type = 4
                rows.each do |row|
                  if (row.css("div.sbjp").text != "")
                    puts "ADMISSION TYPE #{@admission_type}: \n Zavazok: #{row.css("div.sbjp")[0].text}
                         \n Nadobudnutie: #{row.css("div.sbjp")[1].text}
                         \n Datum: #{row.css("div.sbjp")[2].text}
                         \n Zmena: #{row.css("div.sbjp")[3].text}"
                    AdmissionItem.create(admission_id: admission.id, name: row.css("div.sbjp")[0].text, change: row.css("div.sbjp")[3].text, acquisition_date: row.css("div.sbjp")[2].text, acquisition_reason: row.css("div.sbjp")[1].text, category: "monetary_obligation")
                  end
                end
            end
          end
          # inner_tables.each do |table|
          #   rows = inner_tables.css("tr")
          #   puts "ROW #{rows}"
          #   # rows.each do |row|
          #   #   puts "ROW #{row}"
          #   # end
          # end
        end

      end
    end

  end

  def parse_old(data_year)
    require 'rubygems'
    require 'nokogiri'
    require 'open-uri'

    (1..2000).each do |i| #2873
      begin
        page = Nokogiri::HTML(open("http://wwwold.justice.sk/tma.aspx?sudcaID=#{i}&rok=31.12.#{data_year}"))
      rescue OpenURI::HTTPError
        puts "404 YEAR: #{data_year} http://wwwold.justice.sk/tma.aspx?sudcaID=#{i}&rok=31.12.#{data_year}"
      else
        judge_name = page.css("form#Form1 div div div p b")[0].text
        next if (judge_name == ", ")
        judge_name = judge_name.slice(0..judge_name.index(",")-1)

        judge_court = page.css("form#Form1 div div div p span")[0].text
        judge_court = judge_court.slice(0..judge_court.index(",")-1)
        year = "#{data_year}".to_i

        judge = Judge.find_or_create_by(name: judge_name, court: judge_court)
        admission = Admission.create(judge_id: judge.id, year: year)
        (0..2).each do |table_index|
          category2 = page.css("form#Form1 div div div p.uh2m")[table_index].text
          #puts category2

          #tabulka pre konkretny typ admissionu
          inner_table = page.css("form#Form1 div div div table.tbtxt")[table_index+1]
          #puts inner_table

          if (!inner_table.nil?)
            #riadky v danej tabulke
            rows = inner_table.css("tr")

            @admission_type = 0
            case category2
              when "Nehnuteľný majetok"
                @admission_type = 1
                rows.each do |row|
                  if (row.css("td").text != "")
                    puts "ADMISSION TYPE #{@admission_type}: \n Nehnutelnost: #{row.css("td")[1].text}
                         \n Nadobudnutie: #{row.css("td")[2].text}
                         \n Datum: #{row.css("td")[3].text}
                         \n Zmena: "
                    AdmissionItem.create(admission_id: admission.id, name: row.css("td")[1].text, acquisition_date: row.css("td")[3].text, acquisition_reason: row.css("td")[2].text)
                  end
                end
              when "Hnuteľný majetok"
                @admission_type = 2
                rows.each do |row|
                  if (row.css("td").text != "")
                    puts "ADMISSION TYPE #{@admission_type}: \n Hnutelnost: #{row.css("td")[1].text}
                         \n Nadobudnutie: #{row.css("td")[2].text}
                         \n Datum: #{row.css("td")[3].text}
                         \n Cena: #{row.css("td")[7].text}
                         \n Zmena: "
                    AdmissionItem.create(admission_id: admission.id, name: row.css("td")[1].text, value: row.css("td")[7].text, acquisition_date: row.css("td")[3].text, acquisition_reason: row.css("td")[2].text)
                  end
                end
              when "Majetkové práva, záväzky, hodnoty"
                @admission_type = 3
                rows.each do |row|
                  if (row.css("td").text != "")
                    puts "ADMISSION TYPE #{@admission_type}: \n Popis prava: #{row.css("td")[1].text}
                         \n Nadobudnutie: #{row.css("td")[2].text}
                         \n Datum: #{row.css("td")[3].text}
                         \n Cena: #{row.css("td")[7].text}
                         \n Zmena: #{row.css("td")[8].text}"
                    AdmissionItem.create(admission_id: admission.id, name: row.css("td")[1].text, change: row.css("td")[8].text, value: row.css("td")[7].text, acquisition_date: row.css("td")[3].text, acquisition_reason: row.css("td")[2].text)
                  end
                end
            end
          end
        end

      end
    end

  end

end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController

  def stats
    @stats = Judge.stats
  end

  def show
    @judge = Judge.find(params[:id])
  end

  def index
 @filterrific = initialize_filterrific(
      Judge,
      params[:filterrific],
      select_options: {
        sorted_by: Judge.options_for_sorted_by,
      },
      
    ) or return
    @judges= @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/views/judges/_admission.html.erb
<table class="table">
 <caption>Zoznam nehnuteľností</caption>
	<thead>
		<tr>
			<th>Názov</th>
			<th>Dátum nadobudnutia</th>
			<th>Cena</th>
			<th>Dôvod nadobudnutia</th>
			<th>Veľkosť podielu</th>
			<th>Forma vlastníctva</th>
			<th>Zmena</th>
		</tr>
	</thead>
	<tbody>
	 <% admission.admission_items.select{|i| i.category == 'estate'}.each do |item|%>
	 <tr>
	 	<td><%=item.name%></td>
	 	<td><%=item.acquisition_date%></td>
	 		<td><%=item.value > 0 ? item.value : '-' %></td>
	 	<td><%=item.acquisition_reason%></td>
		<td><%=item.ownership_part%></td>
		<td><%=item.ownership_form%></td>
	 	<td><%=item.change%></td>
	 </tr>
 	<%end%>
	</tbody>
<table>

<table class="table">
 <caption>Hnuteľné veci</caption>
	<thead>
		<tr>
			<th>Názov</th>
			<th>Dátum nadobudnutia</th>
			<th>Cena</th>
			<th>Veľkosť podielu</th>
			<th>Forma vlastníctva</th>
			<th>Zmena</th>
		</tr>
	</thead>
	<tbody>
	 <% admission.admission_items.select{|i| i.category == 'chattel'}.each do |item|%>
	 	 <tr>
	 	<td><%=item.name%></td>
	 	<td><%=item.acquisition_date%></td>
	 	<td><%=item.value > 0 ? item.value : '-' %></td>
	 	<td><%=item.acquisition_reason%></td>
		<td><%=item.ownership_part%></td>
		<td><%=item.ownership_form%></td>
	 	<td><%=item.change%></td>
	 </tr>
 	<%end%>
	</tbody>
<table>


<table class="table">
 <caption>Majetkové práva</caption>
	<thead>
		<tr>
			<th>Názov</th>
			<th>Dátum nadobudnutia</th>
			<th>Cena</th>
			<th>Veľkosť podielu</th>
			<th>Forma vlastníctva</th>
			<th>Zmena</th>
		</tr>
	</thead>
	<tbody>
	 <% admission.admission_items.select{|i| i.category == 'property_rights'}.each do |item|%>
	 		 <tr>
	 	<td><%=item.name%></td>
	 	<td><%=item.acquisition_date%></td>
	 	<td><%=item.value > 0 ? item.value : '-' %></td>
	 	<td><%=item.acquisition_reason%></td>
		<td><%=item.ownership_part%></td>
		<td><%=item.ownership_form%></td>
	 	<td><%=item.change%></td>
	 </tr>
 	<%end%>
	</tbody>
<table>


<table class="table">
 <caption>Peňažné záväzky</caption>
	<thead>
		<tr>
			<th>Názov</th>
			<th>Dátum nadobudnutia</th>
			<th>Cena</th>
			<th>Veľkosť podielu</th>
			<th>Forma vlastníctva</th>
			<th>Zmena</th>
		</tr>
	</thead>
	<tbody>
	 <% admission.admission_items.select{|i| i.category == 'monetary_obligation'}.each do |item|%>
	 		 <tr>
	 	<td><%=item.name%></td>
	 	<td><%=item.acquisition_date%></td>
	 	<td><%=item.value > 0 ? item.value : '-' %></td>
	 	<td><%=item.acquisition_reason%></td>
		<td><%=item.ownership_part%></td>
		<td><%=item.ownership_form%></td>
	 	<td><%=item.change%></td>
	 </tr>
 	<%end%>
	</tbody>
<table>


<table class="table">
 <caption>Súbor hnuteľných vecí a majetkových práv</caption>
	<thead>
		<tr>
			<th>Názov</th>
			<th>Dátum nadobudnutia</th>
			<th>Cena</th>
			<th>Veľkosť podielu</th>
			<th>Forma vlastníctva</th>
			<th>Zmena</th>
		</tr>
	</thead>
	<tbody>
	 <% admission.admission_items{|i| i.category = 'chattel_and_property_rights'}.each do |item|%>
	 		 <tr>
	 	<td><%=item.name%></td>
	 	<td><%=item.acquisition_date%></td>
	 	<td><%=item.value > 0 ? item.value : '-' %></td>
	 	<td><%=item.acquisition_reason%></td>
		<td><%=item.ownership_part%></td>
		<td><%=item.ownership_form%></td>
	 	<td><%=item.change%></td>
	 </tr>
 	<%end%>
	</tbody>
<table>

<table class="table">
 <caption>Príjmy a pôžitky</caption>
	<thead>
		<tr>
			<th>Názov</th>
			<th>Dátum nadobudnutia</th>
			<th>Cena</th>
			<th>Veľkosť podielu</th>
			<th>Forma vlastníctva</th>
			<th>Zmena</th>
		</tr>
	</thead>
	<tbody>
	 <% admission.admission_items.select{|i| i.category == 'benefits'}.each do |item|%>
	 	<td><%=item.name%></td>
	<td><%=item.value > 0 ? item.value : '-' %></td>
 	<%end%>
	</tbody>
<table>


<table class="table">
 <caption>Blízke osoby</caption>
	<thead>
		<tr>
			<th>Meno</th>
			<th>Inštitúcia</th>
			<th>Funkcia</th>
		</tr>
	</thead>
	<tbody>
	 <% admission.close_people.each do |p|%>
	 	<td><%=p.name%></td>
	 		<td><%=p.institution%></td>
	 			<td><%=p.function%></td>
 	<%end%>
 	<tbody>
<table>

app/views/judges/_list.html.erb
<%# app/views/students/_list.html.erb %>
<div id="filterrific_results">

  <div>
    <%= page_entries_info judges  %>
  </div>

  <table>
    <tr>
      <th>Name</th>
      <th>Court</th>
    </tr>
    <% judges.each do |judge| %>
      <tr>
        <td><%= link_to(judge.name, judge_path(judge)) %></td>
        <td><%= judge.court %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= will_paginate judges%>

app/views/judges/index.html.erb
<%# app/views/judges/index.html.erb %>
<h1>Judges</h1>

<%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
<%= form_for_filterrific @filterrific do |f| %>

  <div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
                'Reset filters',
                reset_filterrific_url,
        ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>

<%= render(
            partial: 'judges/list',
            locals: { judges: @judges }
    ) %>

app/views/judges/index.js.erb
<% js = escape_javascript(
  render(partial: 'judges/list', locals: { judges: @judges })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/judges/show.html.erb
<h2><%=@judge.name%></h2>
<ul class="nav nav-tabs">
<% @judge.admissions.each do |adm| %>

  <li role="presentation" class="active"><a data-toggle="tab" href="#admission-<%=adm.year%>"><%= adm.year%></a></li>
  <%end%>
</ul>

  <div class="tab-content">
      <% @judge.admissions.each do |adm| %>

      <h4>Majetkové priznanie sudcu za rok <%= adm.year%></h4>
<div id="admission-<%=adm.year%>" class="tab-pane fade in active">

        <%= render 'admission', admission: adm %>
      <%end%>
    </div>